### ISSUE TITLE
RCswitch port

### ISSUE THREAD

**Issue by TurtleForGaming** [tenbaht/sduino#56]
Hi everyone, I'm using an arduino uno to receive 433MHz to control equipment like a lamp. The problem is that arduino is not cheap but little stm8 boards are cheap put is the library supported and if not cant it be ported in the near future ?

**Comment by tenbaht** [comment]
Hi, I am back here and hopefully will have some time again for sduino.
This library sounds interesting, but since I don't have any of these devices I am not planning on porting it any time soon. It doesn't look too complicated, though. So if you are motivated and manage to port it I would be happy to include into the project.

But if the hardware cost is the only reason to use a STM8 you mightbe better off using an Arduino Nano clone. You can find them for $1.90 at aliexpress. That is only $1.20 more than an STM8S and it saves you a lot of additional trouble. https://tenbaht.github.io/sduino/usage/why-stm8/
