### ISSUE TITLE
Newer Arduino IDE version incompatibility 

### ISSUE THREAD

**Issue by Jugulaire** [tenbaht/sduino#68]
Hey, 

I'm working with this tools for a while but when i've tried to use it on newer Arduino IDE version it does not work. 
When you try to upload the IDE say "select upload port first" 

For fixing this issue i've just install the version 1.8.0 of the IDE. 

Note : i'm running Kubuntu 18.04.

**Comment by tenbaht** [comment]
Which board and which programmer? I tried it for the STM8S103 with st-link/v2 and it works for 1.8.5 and 1.8.7 on mint 19 (ubuntu 18.04)
Only stm8gal needs a serial port. If you are using this: Did you chose a port in the IDE at Tools->Port?

**Comment by Jugulaire** [comment]
Hey, sorry for the missing information. 

I use the Generic STM8S103 breakout board with an STM32 based ST LINK V2 from aliexpress.

**Comment by per1234** [comment]
This is a bug in Arduino IDE 1.8.7: https://github.com/arduino/Arduino/issues/8052
It is not caused by anything to do with sduino and there is no way for any change to sduino to work around the problem.

There are a few workarounds:
- Select any port from the Arduino IDE's Tools > Port menu. It doesn't matter what the port is for. If your computer doesn't present any ports and you don't own any devices you can plug in to cause a port to be enumerated then you will not be able to use this workaround.
- Use Arduino IDE 1.8.6 instead of Arduino IDE 1.8.7.
- Use the [hourly build of the Arduino IDE](https://www.arduino.cc/en/Main/Software#hourly). The bug has been fixed since the Arduino IDE 1.8.7 release so the issue will not occur when using the hourly build. Note that the hourly build is primarily intended for beta testing and is not as thoroughly tested as the production releases so there is a chance you might encounter new bugs.

**Comment by tenbaht** [comment]
Thank you very much for this research! I updated the README.md with a link to your workarounds.

**Comment by tenbaht** [comment]
Arduino-1.8.8 is out and this problem seems to be solved there. I hope that helps?
